// Reads the cached daily brief (generated by the cron, never on the render path).
// Falls back to instant computed bullets so pages NEVER call Claude to render.
import { admin } from "./supabase-admin";

export type BriefPoint = { text: string; href: string };

export async function getBrief(): Promise<{ text: string; points: BriefPoint[] }> {
  const today = new Date().toISOString().slice(0, 10);
  const { data } = await admin().from("daily_summaries").select("brief,points").eq("for_date", today).maybeSingle();
  return { text: data?.brief || "", points: (data?.points as BriefPoint[]) || [] };
}

export function fallbackPoints(c: { pending: number; newMsgs: number; tasks: number; raisedMtd: string }): BriefPoint[] {
  const p: BriefPoint[] = [];
  if (c.pending) p.push({ text: `${c.pending} ${c.pending === 1 ? "item" : "items"} waiting for your approval`, href: "/" });
  if (c.newMsgs) p.push({ text: `${c.newMsgs} messages to triage`, href: "/inbox" });
  if (c.tasks) p.push({ text: `${c.tasks} open ${c.tasks === 1 ? "task" : "tasks"}`, href: "/tasks" });
  p.push({ text: `${c.raisedMtd} raised this month`, href: "/donations" });
  return p;
}
