// One-time R4-A re-clean (R-recur-1): strip em-dashes / placeholders from the
// grant_applications.notes and studio_documents.html rows that were stored
// BEFORE the generation-time humanize gate, so old data matches new data.
//
// This is the data half of the two-part fix. The render half (humanize-on-
// render in GrantPeek) already guarantees the *displayed* package is clean
// regardless of when it was made; this pass cleans the *stored* bytes too, so
// any path that reads notes/html raw (PDF, attachments, smart-tools) is clean
// as well, and the bug cannot recur from old rows.
//
// The cleaning logic mirrors lib/humanize.ts exactly (dash + placeholder
// passes). The live-date token ⟦GRANT_DATE⟧ is PRESERVED so the date keeps
// rolling. The old "Prepared/Generated ... Nisria Command Center" footer is
// also stripped from stored studio HTML (R4-7).
//
// Run: node scripts/reclean-r4a.mjs   (token from keychain via the wrapper).

const TOKEN = process.env.SUPABASE_MGMT_TOKEN;
const PROJECT = "ptvhqudonvvszupzhcfl";
if (!TOKEN) { console.error("SUPABASE_MGMT_TOKEN missing"); process.exit(1); }

const ORG = {
  legalName: "By Nisria Inc",
  ein: "88-3508268",
  contactEmail: "sasa@nisria.co",
  contactLine: "By Nisria Inc, sasa@nisria.co, nisria.co",
  donateUrl: "https://nisria.co/donate",
  website: "nisria.co",
};
// long date used to fill any literal [Current Date] stub in a STORED row. The
// header's rolling date uses ⟦GRANT_DATE⟧ (preserved), so this only repairs a
// hard date stub the old generation left behind.
const LONG_DATE = new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric" }).format(new Date());

// ---- mirror of lib/humanize.ts cleaning passes ----
function cleanDashes(s) {
  if (!s) return s;
  const RULE = " HR ";
  return s
    .replace(/^[ \t]*-{3,}[ \t]*$/gm, RULE)
    .replace(/(\d)\s*[—–]\s*(\d)/g, "$1 to $2")
    .replace(/[ \t]*-{2,}[ \t]*/g, ", ")
    .replace(/\s*[—–]\s*/g, ", ")
    .replace(/[—–]/g, ",")
    .replace(/,\s*,/g, ",")
    .replace(/([.,;:!?])\s*,/g, "$1")
    .split(RULE).join("---");
}
function fillPlaceholders(s) {
  if (!s) return s;
  let out = s;
  out = out.replace(/\[(?:insert\s+)?(?:the\s+)?(?:current|today'?s?|date)[^\]]*\]/gi, LONG_DATE);
  out = out.replace(/\[date\]/gi, LONG_DATE);
  out = out.replace(/\[(?:the\s+)?(?:organization|org)[^\]]*(?:contact|details)[^\]]*\]/gi, ORG.contactLine);
  out = out.replace(/\[(?:contact\s+(?:details|info(?:rmation)?)|contact)\]/gi, ORG.contactLine);
  out = out.replace(/\[(?:email|email\s+address)\]/gi, ORG.contactEmail);
  out = out.replace(/\[(?:link|url|donate\s+link|donation\s+link|give\s+link)\]/gi, ORG.donateUrl);
  out = out.replace(/\[website\]/gi, ORG.website);
  out = out.replace(/\[(?:your\s+)?(?:org(?:anization)?\s+)?(?:legal\s+)?name\]/gi, ORG.legalName);
  out = out.replace(/\[ein\]/gi, ORG.ein);
  const lines = out.split("\n");
  const kept = [];
  for (const line of lines) {
    if (!/\[[^\]]*\]/.test(line)) { kept.push(line); continue; }
    const stripped = line.replace(/\[[^\]]*\]/g, "").replace(/[ \t]{2,}/g, " ").trim();
    if (!stripped || /[:\-]\s*$/.test(stripped) || stripped.length < 3) continue;
    kept.push(line.replace(/\s*\[[^\]]*\]\s*/g, " ").replace(/\s{2,}/g, " ").replace(/\s+([.,;:!?])/g, "$1").trimEnd());
  }
  return kept.join("\n");
}
function scrubAiVoice(s) {
  if (!s) return s;
  return s
    .replace(/\bas an? (?:ai|artificial intelligence)(?:\s+(?:language\s+)?(?:model|assistant|chatbot))?\b[,:]?\s*/gi, "")
    .replace(/\bI(?:'m| am) (?:an? )?(?:ai|artificial intelligence|language model|chatbot)\b[.,]?\s*/gi, "")
    .replace(/\b(?:as a|being a|I am a) (?:helpful )?(?:ai )?assistant\b[,.]?\s*/gi, "")
    .replace(/  +/g, " ");
}
function humanize(text) {
  if (text == null) return text;
  let out = String(text);
  out = scrubAiVoice(out);
  out = fillPlaceholders(out);
  out = cleanDashes(out);
  out = out.replace(/\n{3,}/g, "\n\n").replace(/[ \t]+\n/g, "\n");
  return out;
}
// strip the old AI/tool-authorship footer string from stored studio HTML (R4-7)
function stripToolFooter(html) {
  if (!html) return html;
  return html
    .replace(/Prepared with the Nisria Command Center\s*·\s*/g, "")
    .replace(/Generated by the Nisria Command Center\s*·\s*/g, "")
    .replace(/Prepared with the Nisria (?:Document Studio|Command Center)/g, "")
    .replace(/Generated by the Nisria (?:Document Studio|Command Center)/g, "");
}

async function sql(query) {
  const r = await fetch(`https://api.supabase.com/v1/projects/${PROJECT}/database/query`, {
    method: "POST",
    headers: { Authorization: `Bearer ${TOKEN}`, "Content-Type": "application/json", "User-Agent": "Mozilla/5.0" },
    body: JSON.stringify({ query }),
  });
  const txt = await r.text();
  if (!r.ok) throw new Error(`SQL ${r.status}: ${txt}`);
  return JSON.parse(txt);
}
// SQL string literal escaper (single quotes doubled)
const lit = (s) => `'${String(s).replace(/'/g, "''")}'`;

async function main() {
  let grantFixed = 0, studioFixed = 0;

  // --- grant_applications.notes ---
  const grants = await sql(`select id, notes from grant_applications where notes is not null and (notes ~ '[—–]' or notes ~ '\\[[^\\]]+\\]')`);
  for (const g of grants) {
    const cleaned = humanize(g.notes);
    if (cleaned !== g.notes) {
      await sql(`update grant_applications set notes = ${lit(cleaned)} where id = ${lit(g.id)}`);
      grantFixed++;
    }
  }

  // --- studio_documents.html (em-dashes in body + old tool footer) ---
  const docs = await sql(`select id, html from studio_documents where html is not null and (html ~ '[—–]' or html like '%Nisria Command Center%' or html like '%Nisria Document Studio%')`);
  for (const d of docs) {
    // clean only the dashes + footer in the stored HTML. We do NOT run full
    // placeholder-fill on HTML (it is already escaped markup); dashes + the
    // tool-authorship footer are the two things that leak.
    let cleaned = stripToolFooter(d.html);
    cleaned = cleaned
      .replace(/(\d)\s*[—–]\s*(\d)/g, "$1 to $2")
      .replace(/\s*[—–]\s*/g, ", ")
      .replace(/[—–]/g, ",");
    if (cleaned !== d.html) {
      await sql(`update studio_documents set html = ${lit(cleaned)} where id = ${lit(d.id)}`);
      studioFixed++;
    }
  }

  // verify after
  const after = await sql(`select
    (select count(*) from grant_applications where notes ~ '[—–]') as grant_dash,
    (select count(*) from grant_applications where notes ~ '\\[[^\\]]+\\]') as grant_bracket,
    (select count(*) from studio_documents where html ~ '[—–]') as studio_dash,
    (select count(*) from studio_documents where html like '%Nisria Command Center%' or html like '%Nisria Document Studio%') as studio_footer`);

  console.log(JSON.stringify({ grantFixed, studioFixed, after: after[0] }, null, 2));
}
main().catch((e) => { console.error(e); process.exit(1); });
